### ISSUE TITLE
claimscheduler replica in crashloopbackoff after a while

### ISSUE THREAD

**Issue by somejfn** [Mirantis/k8s-externalipcontroller#129] opened 2017-05-15 12:44 UTC
After a while,  one of the 2 claimscheduler replicas goes into crashloopbackoff and logs :

```
W0515 12:30:48.936031       1 client_config.go:438] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
F0515 12:30:59.023533       1 scheduler.go:70] URLs for tprs are not registered: json: cannot unmarshal number 1e+06 into Go value of type int64
```
Version: mirantis/k8s-externalipcontroller:latest on kubernetes 1.5.5 (Coreos/Tectonic).

Work around:  Deleting the faulty POD gets a new one rescheduled.

**Comment by AlexeyKasatkin** [comment] 2017-05-15 15:09
@somejfn , thank you for the feedback.
I'm closing this as a duplicate of https://github.com/Mirantis/k8s-externalipcontroller/issues/128 .
I'll examine it once I have time.

**Closed by AlexeyKasatkin** 2017-05-15 15:09 UTC
